# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ads_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='ads_image/')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
